name: Build FireNet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # نصب WinAppSDK برای Toast Notifications
    - name: Install Windows App SDK
      run: dotnet add "./src/FireNet.UI/FireNet.UI.csproj" package Microsoft.WindowsAppSDK

    - name: Restore dependencies
      run: dotnet restore ./src/FireNet.UI/FireNet.UI.csproj

    - name: Install Toast Notification Toolkit
      run: dotnet add "./src/FireNet.UI/FireNet.UI.csproj" package Microsoft.Toolkit.Uwp.Notifications

    - name: Build
      run: dotnet build ./src/FireNet.UI/FireNet.UI.csproj -c Release

    - name: Publish Build
      run: dotnet publish ./src/FireNet.UI/FireNet.UI.csproj -c Release -o ./release

    # Add Xray-core files
    - name: Add Xray-core
      run: |
        tree /F
        if not exist release\xray-core mkdir release\xray-core
        xcopy xray-core\* release\xray-core\ /E /Y
      shell: cmd

    # add icons to installer
    - name: Add icons
      run: |
        if not exist release\Assets mkdir release\Assets
        if not exist release\Assets\Icons mkdir release\Assets\Icons
        xcopy src\FireNet.UI\Assets\Icons\server.png release\Assets\Icons\ /Y
      shell: cmd

    # Install Inno Setup via Chocolatey
    - name: Install Inno Setup
      run: choco install innosetup -y

    # Build Installer
    - name: Build Installer
      run: iscc installer/fire-installer.iss

    # Upload Installer Artifact (NEW v4)
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FireNet-Installer
        path: installer/output/
        compression-level: 0
